baseURL: "https://brianweinstein.github.io/"
title: Brian Weinstein
# description: Brian's site
paginate: 10
theme: hugo-PaperMod

# publishDir: docs #The directory to where Hugo will write the final static site (the HTML files etc.)
publishDir: ./ #The directory to where Hugo will write the final static site (the HTML files etc.)

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Brian Weinstein
    description: "bw description"
    author: ["Brian Weinstein"]

    # images: "<link or path of image for opengraph, twitter-cards>"
    images: /images

    ShowReadingTime: false
    ShowShareButtons: false
    comments: false
    defaultTheme: light
    disableThemeToggle: true
    disableSpecial1stPost: true

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    label:
        text: "Brian Weinstein" # text to show in the top left of the site
        # icon: /apple-touch-icon.png
        # iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        Title: "hello! 👋"
        Content:
            "
            I'm Brian.


            I manage a team of Data Scientists and Product Analysts at [Slice](https://slicelife.onelink.me/ylsM/8425733). Our team works on our consumer apps, restaurant software, and internal tools; guiding the product direction and helping teams make informed product decisions using data.


            I'm passionate about the intersection of data science, product, and research: from understanding and quantifying user problems to developing and testing product solutions. I also love people management: mentoring my team in data science and communication best practices, finding new opportunities so they can grow, and building a thoughtful and inclusive team culture.


            Previously I managed the Data Science & Research team at WeWork, was a Data Scientist at WeWork, and was a Data Scientist at 1stdibs. I have my Master's degree in applied math and my Bachelor's in physics.


            Outside of data, I enjoy making [pottery](https://www.etsy.com/shop/thingsbybrian/), eating froyo, baking cookies, and running.
            "

            #[Lorem](https://www.google.com) ipsum dolo
        # imageUrl: "<image link>" # optional
        # imageTitle: "<title of image as alt>" # optional
        # imageWidth: 120 # custom size
        # imageHeight: 120 # custom size
        buttons:
            # - name: Posts
            #   url: posts
            # - name: Tags
            #   url: tags

    # home-info mode
    # homeInfoParams:
    #     enabled: false
    #     Title: "hello! 👋"
    #     Content: I'm Brian.

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/brianmweinstein/"
        - name: medium
          url: "https://bweinstein.medium.com/"
        - name: twitter
          url: "https://twitter.com/BriMaster3000"
        - name: github
          url: "https://github.com/BrianWeinstein"
        - name: etsy
          url: "https://www.etsy.com/shop/thingsbybrian/"
        - name: email
          url: "mailto:bweinstein02@gmail.com"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - name: Home
          url: /
          weight: 3 # order of items in the nav
        # - name: About
        #   url: about/
        #   weight: 5 # order of items in the nav
        - name: Writing
          url: writing/
          weight: 50 # order of items in the nav
        # - name: Search
        #   url: search/
          # weight: 500 # order of items in the nav
        # - identifier: categories
        #   name: Categories
        #   url: /categories/
        #   weight: 10 # order of items in the nav
        # - identifier: tags
        #   name: Tags
        #   url: /tags/
        #   weight: 20 # order of items in the nav
